### ISSUE TITLE
error: failed to run custom build command for `nethost-sys v0.5.1`

### ISSUE THREAD

**Issue by ArunGust** [OpenByteDev/netcorehost#25]
I got the below error after update to  **nightly-x86_64-pc-windows-msvc - rustc 1.66.0-nightly (6e95b6da8 2022-10-22)**, any clue ? This was working for a long time. 

Caused by:
  process didn't exit successfully: `H:\TEST\nethost8\target\debug\build\nethost-sys-440c9e86335f8dee\build-script-mod` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Failed to parse json response from nuget.org.: reqwest::Error { kind: Decode, source: Error("missing field `items`", line: 1, column: 689) }', C:\RUST\CARGO\registry\src\github.com-1ecc6299db9ec823\nethost-sys-0.5.1\build\download.rs:119:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

[dependencies]
netcorehost = "0.12.0"
path-absolutize = "^3.0.10"
wchar = "^0.11.0"
json = "*"

**Comment by distantcam** [comment]
Pretty sure this is due to issue https://github.com/OpenByteDev/nethost-sys/issues/2

I got it working with the following.

```toml
[dependencies]
netcorehost = { git = "https://github.com/OpenByteDev/netcorehost" }

[patch.crates-io]
nethost-sys = { git = "https://github.com/OpenByteDev/nethost-sys" }
```
